version: "2.4"

services:

  appsmith_app:
    container_name: appsmith_app
    image: webdevops/php-apache-dev:7.4
    #build: .
    user: "0:0"
    ports:
      - 88:80
    volumes:
      - ../:/app/
    networks:
      - frontend
    environment:
      - "WEB_DOCUMENT_ROOT=/app/public"
      - "PHP_DEBUGGER=none"
      #- "PHP_DEBUGGER=xdebug"
      - "XDEBUG_REMOTE_CONNECT_BACK=true"
      - "XDEBUG_CLIENT_HOST=172.19.0.1"
      - "PHP_OPCACHE_MEMORY_CONSUMPTION=256"
      - "PHP_OPCACHE_MAX_ACCELERATED_FILES=7963"
      - "PHP_OPCACHE_VALIDATE_TIMESTAMPS=10"
      - "PHP_MEMORY_LIMIT=2048M"
      - "PHP_POST_MAX_SIZE=100M"
      - "PHP_UPLOAD_MAX_FILESIZE=100M"

networks:
  frontend:
    external:
      name: frontend
